# Generated by Django 5.2.3 on 2025-06-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_alter_post_options_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default='comment-image/user.png', upload_to='comment-image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='postapp.comment'),
            preserve_default=False,
        ),
    ]
